// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvlxYbiRmomsEB-l30rqyXwuFxXmRtK-0',
    appId: '1:644912730707:web:ba93c7c9ab0aa8bf1d2ca6',
    messagingSenderId: '644912730707',
    projectId: 'stockscrneer-66cbf',
    authDomain: 'stockscrneer-66cbf.firebaseapp.com',
    storageBucket: 'stockscrneer-66cbf.firebasestorage.app',
    measurementId: 'G-6NH7TFZ7TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyisD8wC6nPzO8S-d4qHHsAIvGE3k8Rk8',
    appId: '1:644912730707:android:362c066b8ac175d71d2ca6',
    messagingSenderId: '644912730707',
    projectId: 'stockscrneer-66cbf',
    storageBucket: 'stockscrneer-66cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFfNzy-3nwZQSkEgwDjMX2eD3uyAkpzO8',
    appId: '1:644912730707:ios:50210cf7b2cd7dd61d2ca6',
    messagingSenderId: '644912730707',
    projectId: 'stockscrneer-66cbf',
    storageBucket: 'stockscrneer-66cbf.firebasestorage.app',
    iosBundleId: 'com.example.stockScreener',
  );
}
